import { supabase } from "@/integrations/supabase/client";

const BUCKET = "colaboradores-fotos";
const SIGN_TTL_SECONDS = 60 * 60; // 1 hour

/**
 * Extracts the storage object path (inside the bucket) from a Supabase
 * public/signed URL previously generated by getPublicUrl/createSignedUrl.
 * Returns null if the URL does not match the expected bucket.
 */
export function extractStoragePath(url: string | null | undefined): string | null {
  if (!url) return null;
  const cleaned = url.split("?")[0];
  const marker = `/${BUCKET}/`;
  const idx = cleaned.indexOf(marker);
  if (idx === -1) return null;
  return cleaned.substring(idx + marker.length);
}

/**
 * Given the value stored in `colaboradores.foto_url` (a Supabase public URL),
 * returns a fresh signed URL the authenticated user can load.
 * Falls back to the original URL if the path cannot be parsed.
 */
export async function resolveSignedPhotoUrl(
  storedUrl: string | null | undefined
): Promise<string | null> {
  if (!storedUrl) return null;
  const path = extractStoragePath(storedUrl);
  if (!path) return storedUrl;
  const { data, error } = await supabase.storage
    .from(BUCKET)
    .createSignedUrl(path, SIGN_TTL_SECONDS);
  if (error || !data?.signedUrl) return null;
  return data.signedUrl;
}

/**
 * Resolves an array of stored URLs to signed URLs in parallel,
 * returning a map keyed by the original URL.
 */
export async function resolveSignedPhotoUrls(
  storedUrls: (string | null | undefined)[]
): Promise<Record<string, string>> {
  const unique = Array.from(new Set(storedUrls.filter((u): u is string => !!u)));
  const entries = await Promise.all(
    unique.map(async (u) => [u, await resolveSignedPhotoUrl(u)] as const)
  );
  return Object.fromEntries(entries.filter(([, v]) => !!v) as [string, string][]);
}
