
INSERT INTO categorias_financeiras (nome_categoria, grupo_dre, tipo) VALUES
('Receita com Vendas', 'Receita Bruta', 'receita'),
('Impostos Sobre Vendas', 'Deduções', 'despesa'),
('Custos Variáveis', 'Custos Variáveis', 'despesa'),
('Gastos com Pessoal', 'Despesas Operacionais', 'despesa'),
('Gastos com Ocupação', 'Despesas Operacionais', 'despesa'),
('Gastos com Serviços de Terceiros', 'Despesas Operacionais', 'despesa'),
('Gastos com Marketing', 'Despesas Operacionais', 'despesa'),
('Receitas não Operacionais', 'Resultado não Operacional', 'receita'),
('Gastos não Operacionais', 'Resultado não Operacional', 'despesa'),
('Imposto de Renda e CSLL', 'Impostos', 'despesa'),
('Investimentos', 'Investimentos', 'despesa'),
('Transferências e Ajustes de Saldo (Déb)', 'Transferências', 'despesa'),
('Transferências e Ajustes de Saldo (Cré)', 'Transferências', 'receita'),
('Logística operacional', 'Despesas Operacionais', 'despesa'),
('Gastos com sistemas, site e aplicativos', 'Despesas Operacionais', 'despesa'),
('Gastos com manutenção - produção', 'Despesas Operacionais', 'despesa'),
('Despesas com brindes e presentes', 'Despesas Operacionais', 'despesa'),
('Embalagem geral', 'Custos Variáveis', 'despesa'),
('Importação', 'Custos Variáveis', 'despesa'),
('Compras de equipamentos', 'Investimentos', 'despesa'),
('Taxas de Gateway', 'Deduções', 'despesa'),
('Estornos', 'Deduções', 'receita'),
('Logística de vendas', 'Despesas Operacionais', 'despesa'),
('Comissão de vendedores', 'Despesas Operacionais', 'despesa'),
('Parcelamento de saldo do cartão de crédito', 'Financeiro', 'despesa'),
('Despesas administrativas', 'Despesas Operacionais', 'despesa');
