ALTER TABLE public.produtos
  ADD COLUMN IF NOT EXISTS imposto_percentual NUMERIC DEFAULT 10,
  ADD COLUMN IF NOT EXISTS comissao_percentual NUMERIC DEFAULT 1,
  ADD COLUMN IF NOT EXISTS cupom_percentual NUMERIC DEFAULT 12,
  ADD COLUMN IF NOT EXISTS parcelamento_percentual NUMERIC DEFAULT 9.05,
  ADD COLUMN IF NOT EXISTS custo_corte NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS custo_costura NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS custo_embalagem NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS preco_venda_sugerido NUMERIC;

NOTIFY pgrst, 'reload schema';